### ISSUE TITLE
remove "-e" from userparameter_diskstats.conf

### ISSUE THREAD

**Issue by Slapper** [grundic/zabbix-disk-performance#10]
Hello,

You should remove "-e" option in awk under userparameter_diskstats.conf to get correct data from /sys/class/block/$1/stat . Auto-discovery script works without any issues.

**Comment by grundic** [comment]
Hello @Slapper, thank you for your ticket.
I tested it some time ago after #9 proposal and it worked fine in VirtualBox. Could you please describe why it would not work?
Also, maybe @Spindel could comment this somehow?

**Comment by Spindel** [comment]
-e is a gnu awk option. Might not be standard on mawk, which Debian (sometimes) uses.
Which is used on Debian depends on the phase of the Moon, and what software got installed in what order, due to alternatives.

Removing it could work. Depends on the awk implementation.

**Comment by Slapper** [comment]
Hi @grundic !

I test it on centos 6 installation. Nothing special awk just the default package :

```
rpm -qa |grep awk
gawk-3.1.7-10.el6_7.3.x86_64

```

If you try to run the command through the cli you will get : 

```
root@server# awk -e '{print $9}' /sys/class/block/vda/stat
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
Usage: awk [POSIX or GNU style options] [--] 'program' file ...
POSIX options:		GNU long options:
	-f progfile		--file=progfile
	-F fs			--field-separator=fs
	-v var=val		--assign=var=val
	-m[fr] val
	-O			--optimize
	-W compat		--compat
	-W copyleft		--copyleft
	-W copyright		--copyright
	-W dump-variables[=file]	--dump-variables[=file]
	-W exec=file		--exec=file
	-W gen-po		--gen-po
	-W help			--help
	-W lint[=fatal]		--lint[=fatal]
	-W lint-old		--lint-old
	-W non-decimal-data	--non-decimal-data
	-W profile[=file]	--profile[=file]
	-W posix		--posix
	-W re-interval		--re-interval
	-W source=program-text	--source=program-text
	-W traditional		--traditional
	-W usage		--usage
	-W use-lc-numeric	--use-lc-numeric
	-W version		--version

To report bugs, see node `Bugs' in `gawk.info', which is
section `Reporting Problems and Bugs' in the printed version.

gawk is a pattern scanning and processing language.
By default it reads standard input and writes standard output.

Examples:
	gawk '{ sum += $1 }; END { print sum }' file
	gawk -F: '{ print $1 }' /etc/passwd
```

The same output i get with the zabbix_get command.

**Comment by Spindel** [comment]
Then toss the -e flag :)

**Comment by grundic** [comment]
Yep, looks like `-e` flag could be safely removed. Thank you, guys!
