### ISSUE TITLE
Agent fails to start

### ISSUE THREAD

**Issue by CobaltSparkz** [grundic/zabbix-disk-performance#11]
After installing the config and script, the Zabbix Agent fails to start. If I remove the two items, the agent starts fine. Any ideas?

Many thanks

**Comment by grundic** [comment]
Hi @CobaltSparkz,
Could you please take a look at logs, they should be somewhere in /var/log/zabbix or /tmp. Maybe you're missing some dependency (python?) maybe something else.. Logs should help a lot.

**Comment by CobaltSparkz** [comment]
Hey! I think I found the error - Will be doing some testing over the next day or two, see what I can see. I believe the error came from when I had some previous information within the zabbix agent config, so I'll try again :)

**Comment by grundic** [comment]
Cool, good luck then! :)
And stay in touch.

**Comment by CobaltSparkz** [comment]
Hey!

Did a reinstall of it all, no avail. 

Which logs are the ones you'd like? I'm assuming zabbix_agentd.log (Apologies, I'm not too clued up on all this!)

**Comment by grundic** [comment]
@CobaltSparkz,
I was interested in logs to solve your problem. If you are fine and resolve it already then I don't need them anymore :)

**Comment by CobaltSparkz** [comment]
It still doesn't work, it's what I meant by "no avail" - Apologies for not being clearer!

**Comment by grundic** [comment]
I would suggest taking a look at both server and client logs. If you can upload them somewhere I can try to look at them.

**Comment by CobaltSparkz** [comment]
Hey Grundic,

My apologies for not having gotten back to you sooner, it's been manic - I'll endeavour to get this seen to during the week, see what I can come up with, regarding logs :)

Thanks again for your help!

**Comment by grundic** [comment]
Sure, keep informed.

**Comment by grundic** [comment]
@CobaltSparkz, I'll close it so it won't confuse others. If you have this problem again, let's create another ticket for that.
