### ISSUE TITLE
Export template to version 3.0

### ISSUE THREAD

**Issue by grundic** [grundic/zabbix-disk-performance#12]
> Please export the template to zabbix 3.0.
> When imported your template just Applications Items 1| Triggers 0| Graphics 0 |Screens 0|Discovery 1| Web 0| came ....

From [this](https://github.com/grundic/zabbix-disk-performance/commit/c17c39d6ed655d3b5dacb17a48c3ce6efd10400f#commitcomment-17707498) comment.

**Comment by JustDevNull** [comment]
Hi, any news with this?

**Comment by grundic** [comment]
Nope yet.. Will do my best to close it shortly..
I'm not working with Zabbix right now, so it difficult to support it. But I'll take a look what could be done.

**Comment by jojen** [comment]
This would be great if there is a template also working for version 3

**Comment by grundic** [comment]
Just tried to import original template to Zabbix 3.0.4 from Docker -- everything is fine. Have not seen any errors or something...
If you can't find graphs and item prototypes, then check `Discovery rules`, as this template create them individually for each discovered disk/partition.

**Comment by jojen** [comment]
Yes thank you. It's working now :)

**Comment by grundic** [comment]
I've added [explanation](https://github.com/grundic/zabbix-disk-performance/commit/cb919faf8010610c99558d4c8e271bd47ed75a75) to readme, so now it should be clear.
