### ISSUE TITLE
zabbix 3.2 disk read data none

### ISSUE THREAD

**Issue by 1a2a3a4a5a6a7a** [grundic/zabbix-disk-performance#15]
[root@monitor zabbix]# zabbix_get -s 127.0.0.1 -k "custom.vfs.dev.read.sectors[sda2]"
471815

read data display ok

but. zabbix web page lastdata or graph read data not displayed ㅠㅠ

help

**Comment by grundic** [comment]
Hello, @1a2a3a4a5a6a7a.

It could be that sometimes data is not displayed immediately. Have you any succeed with it so far?

**Comment by 1a2a3a4a5a6a7a** [comment]
Hello~ grundic

No ㅠㅠ Still not visible on the web.
I have been monitoring for about 3 days but it is not visible yet.

**Comment by grundic** [comment]
If you can get data using `zabbix_get`, zabbix server should be able to do the same.

Try some of these: 
* detach template, clean data and attach again
* change refresh of low level discovery from 3600 seconds to 10
* running `zabbix_get` command from zabbix server, using remove ip address of the agent
* make sure you are testing the same agent through `zabbix_get` and in web
* inspect logs at /var/log/zabbix/ for some suspicious errors

**Comment by grundic** [comment]
Great, glad you could solve it!
