### ISSUE TITLE
ZBX_NOTSUPPORTED: Unsupported item key.

### ISSUE THREAD

**Issue by astatinede** [grundic/zabbix-disk-performance#16]
Hallo,
first thank you very much for the super template.

I have followed the guide and all the files installed.
But when i tried to test the command " zabbix_get -s 127.0.0.1 -k "custom.vfs.discover_disks"",
i got 

ZBX_NOTSUPPORTED: Unsupported item key.

Would you please tell me how to solve the problem?
My Sever is running debian and zabbix 2.4. Just upgraded from 2.2
Thanks.

**Comment by grundic** [comment]
Hello, @astatinede!

I would recommend checking the correctness of installation of userparameter_diskstats.conf. Did you put it to the correct directory?
If you're sure that you did, then have you restarted Zabbix after that? Also you can try to inspect logs at /var/logs/zabbix or something like that.

**Comment by astatinede** [comment]
Thank you for your feedback.
I checked again, the userparameter_diskstats.conf file is under the new created /etc/zabbix/zabbix_agentd.d.
I also found another default path /etc/zabbix/zabbix_agentd.conf.d   I did move the conf file to this path and tested again. Still get notsupported.

Below is the output from zabbix_server.log after restart. Seems everthing good.
Would you please tell me how can I check if zabbix server has loaded the userparameter_diskstats.conf successfully? Or how can I configure Zabbix enforce to load the conf?
> 8069:20161117:083249.509 Starting Zabbix Server. Zabbix 2.4.8 (revision 59539).
  8069:20161117:083249.509 ****** Enabled features ******
  8069:20161117:083249.509 SNMP monitoring:           YES
  8069:20161117:083249.509 IPMI monitoring:            NO
  8069:20161117:083249.509 WEB monitoring:            YES
  8069:20161117:083249.509 VMware monitoring:         YES
  8069:20161117:083249.509 Jabber notifications:       NO
  8069:20161117:083249.509 Ez Texting notifications:  YES
  8069:20161117:083249.509 ODBC:                       NO
  8069:20161117:083249.509 SSH2 support:               NO
  8069:20161117:083249.509 IPv6 support:              YES
  8069:20161117:083249.509 ******************************
  8069:20161117:083249.509 using configuration file: /usr/local/etc/zabbix_server.conf
  8069:20161117:083249.517 current database version (mandatory/optional): 02040000/02040000
  8069:20161117:083249.517 required mandatory version: 02040000
  8069:20161117:083249.550 server #0 started [main process]
  8071:20161117:083249.551 server #1 started [configuration syncer #1]
  8072:20161117:083249.551 server #2 started [db watchdog #1]
  8073:20161117:083249.551 server #3 started [poller #1]
  8074:20161117:083249.552 server #4 started [poller #2]
  8075:20161117:083249.552 server #5 started [poller #3]
  8076:20161117:083249.553 server #6 started [poller #4]
  8077:20161117:083249.553 server #7 started [poller #5]
  8078:20161117:083249.553 server #8 started [unreachable poller #1]
  8079:20161117:083249.554 server #9 started [trapper #1]
  8080:20161117:083249.554 server #10 started [trapper #2]
  8081:20161117:083249.554 server #11 started [trapper #3]
  8083:20161117:083249.555 server #13 started [trapper #5]
  8085:20161117:083249.556 server #15 started [alerter #1]
  8086:20161117:083249.556 server #16 started [housekeeper #1]
  8087:20161117:083249.556 server #17 started [timer #1]
  8088:20161117:083249.557 server #18 started [http poller #1]
  8082:20161117:083249.560 server #12 started [trapper #4]
  8094:20161117:083249.560 server #24 started [escalator #1]
  8093:20161117:083249.562 server #23 started [history syncer #4]
  8090:20161117:083249.566 server #20 started [history syncer #1]
  8084:20161117:083249.566 server #14 started [icmp pinger #1]
  8095:20161117:083249.567 server #25 started [proxy poller #1]
  8096:20161117:083249.567 server #26 started [self-monitoring #1]
  8091:20161117:083249.567 server #21 started [history syncer #2]
  8092:20161117:083249.568 server #22 started [history syncer #3]
  8089:20161117:083249.571 server #19 started [discoverer #1]

**Comment by astatinede** [comment]
Ha, problem solved.
I added Include=/etc/zabbix/zabbix_agentd.d/ in zabbix_agentd.conf and restarted zabbix_agentd

Thanks for the tipps.

**Comment by grundic** [comment]
I was just going to ask you to check this configuration file. 
Glad it worked!

**Comment by AndrStnz** [comment]
Just wanted to add 

The Include Option in /etc/zabbix/zabbix_agentd.conf hast to be: 

> Include=/etc/zabbix/zabbix_agentd.d/
 ## **not**
> Include=/etc/zabbix/zabbix_agentd.d/*.conf 

Theoretically they should both work, but sadly didnt.
