### ISSUE TITLE
Not able to retreive data

### ISSUE THREAD

**Issue by donbertos** [grundic/zabbix-disk-performance#4]
[root@Zabbix zabbix-disk-performance-master]# zabbix_get -s 192.168.xxx.xxx -k "custom.vfs.dev.write.sectors[sda]"
52084

I am able to return the data from the README, but when template is applied to a host.. no new items or graphs appear

should i see anything when i run the command:
 zabbix_get -s 192.168.xxx.xxx -k "custom.vfs.discover_disks"

?

edit: I am seeing an error in the discovery rule: "Value should be a JSON object"

**Comment by grundic** [comment]
Looks like a script for low-level discovery is not working. Try to run it manually on agent host.
I will close this ticket as it is old. If you still have issues - feel free to reopen it.
