### ISSUE TITLE
The template isn't compatible with zabbix 2.4

### ISSUE THREAD

**Issue by myliyifei** [grundic/zabbix-disk-performance#5]
I try to import this template into 2.4.4, but the items  show 0.

Template Disk Performance	Applications (1)	Items (0)	Triggers (0)	Graphs (0)	Screens (0)	Discovery (1)	Web (0)	-	-

**Comment by grundic** [comment]
Hello! There are not direct items in this template. All items are based on explored disks. And the disks are explored via [low-level-discovery](https://www.zabbix.com/documentation/2.4/manual/discovery/low_level_discovery). 
Click on `Discovery (1) ` -- there you will find all items.

**Comment by myliyifei** [comment]
thanks for your reply, I will try this.

2015-04-12 14:53 GMT+08:00, Grigory Chernyshev <notifications@github.com>:

**Comment by myliyifei** [comment]
thank you. It works
