### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by dimovnike** [grundic/zabbix-disk-performance#7]
hi, i encountered these errors when importing template:

mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:450]
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('Disk discovery','0','','','3600','0','','','0','0','','0','','','','','0','','','','','',Array,'30','','custom.vfs.discover_disks','','10109','1','4','0',NULL,'23952')] [Unknown column 'Array' in 'field list']
SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('Disk discovery','0','','','3600','0','','','0','0','','0','','','','','0','','','','','',Array,'30','','custom.vfs.discover_disks','','10109','1','4','0',NULL,'23952')".

**Comment by brainsqueezer** [comment]
Same here. Anyone had time to review this?

**Comment by grundic** [comment]
Hey guys, sorry for late reply.
Could you please specify Zabbix version you are using?

**Comment by adinindu** [comment]
I have the same issue. Using Zabbix 2.2

**Comment by grundic** [comment]
@adinindu I will take a look again.
Thank you.

**Comment by lonstanley** [comment]
same error for me...
on zabbix 2.2

**Comment by grundic** [comment]
Hi guys!
Again, sorry for delay -- was very busy.
The issue was fixe in c17c39d.

Wish you all great holidays and happy new year!
